from typing import TypedDict


class SignalData(TypedDict):
    ticker: str
    direction: str  # Direction value
    confidence: float
    event_type: str  # EventType value
    reasoning: str


class SignalState(TypedDict):
    event_id: int
    headline: str
    body: str | None
    ticker_hints: list[str]  # pre-resolved symbols from ingestion
    companies: list[str]  # extracted by Haiku
    ticker: str | None  # single validated ticker (or None → error path)
    signal: SignalData | None  # generated by Sonnet
    error: str | None
    total_cost_usd: float
    langfuse_trace_id: str | None
